### ISSUE TITLE
Uncaught Error: Can't find end of central directory : is this a zip file ? 

### ISSUE THREAD

**Issue by BigtigerWW** [mwilliamson/mammoth.js#329] opened 2022-06-28 09:26 UTC
Guys, when I use docx to convert to HTML, there is an error in convertToHtml(). I checked other answers, but it didn't solve my problem. I hope the big guy can answer
![1](https://user-images.githubusercontent.com/108333026/176144466-816473b1-0bf5-49cf-a932-b4a622a11307.png)
![2](https://user-images.githubusercontent.com/108333026/176144482-67697a2b-cab7-442d-8554-b1d6b991d32a.png)

**Comment by mwilliamson** [comment] 2022-06-28 21:32
Could you provide a minimal example document?

**Comment by BigtigerWW** [comment] 2022-06-29 00:28
> 你能提供一个最小的示例文档吗？

Thank you for your reply, I am using vue2, send the request through axios (the received data type is arrayBuffer), the previewed file is of docx type, and the mammoth version is 1.4.21
![1](https://user-images.githubusercontent.com/108333026/176326094-98ae4c5f-2661-4aa0-b962-c320b4d423a0.png)
![12](https://user-images.githubusercontent.com/108333026/176326107-ab7edf4b-496d-4438-819a-d1fe451f3a64.png)

**Comment by mwilliamson** [comment] 2022-06-29 08:12
Could you include the actual docx file?

**Comment by BigtigerWW** [comment] 2022-07-04 01:34
> 
[Doc12138.docx](https://github.com/mwilliamson/mammoth.js/files/9035930/Doc12138.docx)
Sorry for the late reply, this is the docx file I use

**Comment by mwilliamson** [comment] 2022-07-04 07:47
How did you make that file? Docx files are normally ZIP files, which that doesn't seem to be.

**Comment by BigtigerWW** [comment] 2022-07-05 04:19
![1](https://user-images.githubusercontent.com/108333026/177248513-7522f876-1c63-459f-8ee7-bec4e07e8176.png)
I just create a new file

**Comment by mwilliamson** [comment] 2022-07-05 07:10
According to `file`, the format is `Composite Document File V2 Document`, so the file looks more like a `.doc` file than a `.docx` file, which I'm afraid Mammoth doesn't support.

**Comment by BigtigerWW** [comment] 2022-07-06 05:31
> 
I will try to create other .docx files, thanks for the answer ^_^

**Comment by garrettApproachableGeek** [comment] 2022-07-18 22:28
We are having the same issue 
```
Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
```
Here is an example docx file:
[test_file.docx](https://github.com/mwilliamson/mammoth.js/files/9136061/test_file.docx)
Which using `file` is not a `Composite Document File V2 Document` but rather a `Microsoft Word 2007+`

**Comment by mwilliamson** [comment] 2022-07-18 22:30
> We are having the same issue
> 
> ```
> Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
> ```
> 
> Here is an example docx file: [test_file.docx](https://github.com/mwilliamson/mammoth.js/files/9136061/test_file.docx) Which using `file` is not a `Composite Document File V2 Document` but rather a `Microsoft Word 2007+`

Could you make a new issue with reproduction steps? I've tried using that file myself, and it seems to work fine.

**Comment by mwilliamson** [comment] 2022-07-18 22:31
Closing this issue since I don't think there's anything to address in this instance.

**Closed by mwilliamson** 2022-07-18 22:31 UTC

**Comment by cumt-robin** [comment] 2022-12-02 02:00
it looks like mammoth.js doesn't support `.doc` document. Is there any alternatives ?

**Comment by brady-man-847** [comment] 2023-12-27 02:45
I found it's problem caused by JSZip.
JSZip cannot unzip arraybuffer without actual file path.

**Comment by mrpengxinwen** [comment] 2024-11-08 07:08
We are  having the same issue, we found that this is due to the docx document has been watermarked，but we don't know how to  remove the watermarks before reading file。May I ask if anyone can help me？
