### ISSUE TITLE
Some 'bold' tags are not considered in the HTML generation

### ISSUE THREAD

**Issue by jensscheerlinck** [mwilliamson/mammoth.js#77] opened 2016-04-15 15:15 UTC
Specifically, the closing of the bold tags before the closing of the paragraph.

Output:

```html
<p>ΚΩΔΙΚΑΣ ΔΙΟΙΚΗΤΙΚΗΣ ΔΙΑΔΙΚΑΣΙΑΣ &#8211;<br />↩
ΝΟΜΟΣ 2690/1999</p>↩
<p><strong>ΤΜΗΜΑ ΔΙΑΡΚΟΥΣ ΚΩΔΙΚΑ ΝΟΜΟΘΕΣΙΑΣ &#8211;<br />↩
«ΡΑΠΤΑΡΧΗΣ»</strong></p>↩
<p><strong>ΥΠΟΥΡΓΕΙΟ ΕΣΩΤΕΡΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΗΣ ΑΝΑΣΥΓΚΡΟΤΗΣΗΣ</p>↩
<p>ΔΙΟΙΚΗΤΙΚΗ ΜΕΤΑΡΡΥΘΜΙΣΗ ΚΑΙ ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΑΚΥΒΕΡΝΗΣΗ</p>↩
<p>ΓΕΝΙΚΗ ΔΙΕΥΘΥΝΣΗ ΟΙΚΟΝΟΜΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΩΝ ΥΠΗΡΕΣΙΩΝ</p>↩
<p>ΔΙΕΥΘΥΝΣΗ ΠΡΟΜΗΘΕΙΩΝ, ΥΠΟΔΟΜΩΝ ΚΑΙ ΔΙΑΧΕΙΡΙΣΗΣ ΥΛΙΚΟΥ</strong></p>↩
```
Input:

```xml
<w:p w:rsidR="00F70CD6" w:rsidRPr="00414C5A" w:rsidRDefault="00F70CD6" w:rsidP="005B61D4"><w:pPr><w:autoSpaceDE w:val="0"/><w:autoSpaceDN w:val="0"/><w:adjustRightInd w:val="0"/><w:jc w:val="center"/><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria"/></w:rPr></w:pPr><w:r w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr><w:t xml:space="preserve">ΥΠΟΥΡΓΕΙΟ ΕΣΩΤΕΡΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΗΣ ΑΝΑΣΥΓΚΡΟΤΗΣΗΣ </w:t></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr><w:br/></w:r><w:r w:rsidR="00414C5A" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr><w:br/></w:r><w:r w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr><w:t>ΔΙΟΙΚΗΤΙΚΗ ΜΕΤΑΡΡΥΘΜΙΣΗ ΚΑΙ ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΑΚΥΒΕΡΝΗΣΗ</w:t></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/></w:rPr><w:br/></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr><w:br/></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/></w:rPr><w:t>ΓΕΝΙΚΗ ΔΙΕΥΘΥΝΣΗ ΟΙΚΟΝΟΜΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΩΝ ΥΠΗΡΕΣΙΩΝ</w:t></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/></w:rPr><w:br/></w:r><w:r w:rsidR="00FA4D53" w:rsidRPr="00414C5A"><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria" w:cs="Book Antiqua,Bold"/><w:b/><w:bCs/></w:rPr><w:br/><w:t>ΔΙΕΥΘΥΝΣΗ ΠΡΟΜΗΘΕΙΩΝ, ΥΠΟΔΟΜΩΝ ΚΑΙ ΔΙΑΧΕΙΡΙΣΗΣ ΥΛΙΚΟΥ</w:t></w:r></w:p><w:p w:rsidR="00414C5A" w:rsidRPr="00414C5A" w:rsidRDefault="00414C5A" w:rsidP="00FA4D53"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:ascii="Cambria" w:hAnsi="Cambria"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:pPr></w:p>
```

Note: we installed mammoth via npm

Source documents:
[xml-document.txt](https://github.com/mwilliamson/mammoth.js/files/221225/xml-document.txt)
[html-output.txt](https://github.com/mwilliamson/mammoth.js/files/221226/html-output.txt)

**Comment by mwilliamson** [comment] 2016-04-15 18:04
Thanks for the report. Could you provide the entire original document so that I can reproduce the issue?

**Comment by mwilliamson** [comment] 2016-04-15 18:16
In fact, if you could produce the smallest document that still seems to exhibit the issue, that would be most useful.

**Comment by jensscheerlinck** [comment] 2016-04-15 18:27
Just tested it with this small snippet, which still displays the problem:
[test.docx](https://github.com/mwilliamson/mammoth.js/files/221519/test.docx)

**Comment by mwilliamson** [comment] 2016-04-15 18:36
Hmm, I just tried it out and got this output:

```html
<p>ΚΩΔΙΚΑΣ ΔΙΟΙΚΗΤΙΚΗΣ ΔΙΑΔΙΚΑΣΙΑΣ - <br />ΝΟΜΟΣ 2690/1999</p><p><strong>ΤΜΗΜΑ ΔΙΑΡΚΟΥΣ ΚΩΔΙΚΑ ΝΟΜΟΘΕΣΙΑΣ - <br />«ΡΑΠΤΑΡΧΗΣ»</strong></p><p><strong>ΥΠΟΥΡΓΕΙΟ ΕΣΩΤΕΡΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΗΣ ΑΝΑΣΥΓΚΡΟΤΗΣΗΣ <br /><br />ΔΙΟΙΚΗΤΙΚΗ ΜΕΤΑΡΡΥΘΜΙΣΗ ΚΑΙ ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΑΚΥΒΕΡΝΗΣΗ<br /><br />ΓΕΝΙΚΗ ΔΙΕΥΘΥΝΣΗ ΟΙΚΟΝΟΜΙΚΩΝ ΚΑΙ ΔΙΟΙΚΗΤΙΚΩΝ ΥΠΗΡΕΣΙΩΝ<br /><br />ΔΙΕΥΘΥΝΣΗ ΠΡΟΜΗΘΕΙΩΝ, ΥΠΟΔΟΜΩΝ ΚΑΙ ΔΙΑΧΕΙΡΙΣΗΣ ΥΛΙΚΟΥ</strong></p><p><br /></p><p><em>Αθήνα 31/10/2015<br /></em></p>
```

Which seems well-formed to me. Are you getting different output? If so, then could I ask what version of Mammoth you're running, and what platform you're running on (version of node/browser, operating system)?

**Comment by jensscheerlinck** [comment] 2016-04-15 18:49
I get the same output and you are right. This output does seem correct. 
I will try to recreate the output from the initial comment with the smallest possible Word document.

**Comment by mwilliamson** [comment] 2016-05-04 21:46
Did you manage to find an example of incorrectly nested HTML being generated?

**Comment by mwilliamson** [comment] 2016-05-26 21:35
Closing since I don't think there's anything I can do at the moment. Feel free to reopen if you can provide reproduction steps.

**Closed by mwilliamson** 2016-05-26 21:35 UTC
Labels: Cannot reproduce
