### ISSUE TITLE
Fails to open file due to failure to find Target in Relationships (.rels) file due to leading forward slash

### ISSUE THREAD

**Issue by terryjbutler** [mwilliamson/mammoth.js#218] opened 2019-11-06 13:01 UTC
Trying to load a .docx created using DocumentFormat.OpenXml, I have faced a problem whereby `docxFile.exists(target)` fails due to the leading forward slash for the Target paths (e.g. bad:`Target="/docProps/app.xml"` vs good:`Target="docProps/app.xml"`):

Broken version:

```
<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="/docProps/app.xml" Id="rId3" />
    <Relationship Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="/docProps/core.xml" Id="rId2" />
    <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="/word/document2.xml" Id="rId1" />
</Relationships>
```

Working version - files created by Word turn out as follows (Note the lack of forward slash):

```
<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml" Id="rId3" />
    <Relationship Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml" Id="rId2" />
    <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document2.xml" Id="rId1" />
</Relationships>
```

This appears to be breaking the discovery of the Relationship Targets and causing the library to produce the following error `Could not find main document part. Are you sure this is a valid .docx file?` in the function `findPartPaths()` in file `docx-reader.js`.

**Comment by mwilliamson** [comment] 2019-11-06 22:04
Could you provide a minimal example document?

**Comment by terryjbutler** [comment] 2019-11-07 10:17
Hi Michael, 

Thanks for getting back to me so quickly. 

I've attached two files, both saved from the same .dotx template created in Word. The OpenXML saved version has the leading forward slash for the .rels document Target. 

[saved-from-openxml-lib-broken.docx](https://github.com/mwilliamson/mammoth.js/files/3818998/saved-from-openxml-lib-broken.docx)
[saved-from-word-working.docx](https://github.com/mwilliamson/mammoth.js/files/3818999/saved-from-word-working.docx)

**Comment by mwilliamson** [comment] 2019-11-10 13:18
Hmm, the document seems to work correctly when I try it out. Some platform-specific code might have accidentally slipped into how the paths in the zip are handled: would you happen to be on Windows?

Could you post the full error and stack trace?

**Comment by mwilliamson** [comment] 2019-11-10 13:36
Also, if you could replace `findPartPath` in `docx-reader.js` with the following and see what it outputs, that would be handy.

```javascript
function findPartPath(options) {
    var docxFile = options.docxFile;
    var relationships = options.relationships;
    var relationshipType = options.relationshipType;
    var basePath = options.basePath;
    var fallbackPath = options.fallbackPath;

    var targets = relationships.findTargetsByType(relationshipType);
    console.log();
    console.log(targets);
    var normalisedTargets = targets.map(function(target) {
        return stripPrefix(zipfile.joinPath(basePath, target), "/");
    });
    console.log(normalisedTargets);
    var validTargets = normalisedTargets.filter(function(target) {
        return docxFile.exists(target);
    });
    console.log(validTargets);
    if (validTargets.length === 0) {
        return fallbackPath;
    } else {
        return validTargets[0];
    }
}
```

**Comment by mwilliamson** [comment] 2021-08-01 09:56
Closing since I can't reproduce.

**Closed by mwilliamson** 2021-08-01 09:56 UTC
Labels: Need more info
