### ISSUE TITLE
Paragraph which are center aligned not rendered as centered

### ISSUE THREAD

**Issue by davefinarb** [mwilliamson/mammoth.js#210] opened 2019-08-27 14:45 UTC
when parsing a document, the out is not aligned if a paragraph is center aligned

**Comment by mwilliamson** [comment] 2019-08-28 22:26
I think this is a duplicate of #130: Mammoth intentionally doesn't copy the exact formatting of the original document, but instead maps Word styles to the appropriate HTML. If you create a Word style that centres your paragraphs, you can map that style to the corresponding HTML.

**Closed by mwilliamson** 2019-08-28 22:26 UTC

**Comment by durandarthur** [comment] 2024-11-15 19:07
Just curious, what prompted this decision ?
I believe that most users who would be using this package would want alignment to be transferred by default.
It would be unnecessary work to tell users to make custom word styles when most people use the default alignment features.
