### ISSUE TITLE
missing "/" character on selfClosing

### ISSUE THREAD

**Issue by ltanh1906** [mwilliamson/mammoth.js#423] opened 2024-09-30 04:25 UTC
I upload an word file with image but result return an tag with ">" close instead of "/>"

**Comment by mwilliamson** [comment] 2024-09-30 18:25
Could you provide the steps to reproduce the problem, including a minimal example document, the actual HTML being generated, and the HTML you'd expect?

**Comment by mwilliamson** [comment] 2024-10-09 21:44
I'm closing this due to the lack of reproduction steps, but I'm happy to reopen if you can provide them.

**Closed by mwilliamson** 2024-10-09 21:44 UTC
