### ISSUE TITLE
Blank lines in style map cause error

### ISSUE THREAD

**Issue by jwhitmarsh** [mwilliamson/mammoth.js#94] opened 2016-09-16 11:03 UTC
Running `mammoth test/.docx test.html --style-map=my-style-map` where `my-style-map` is 

``` 
p[style-name='Aside Heading'] => div.aside > h2:fresh
p[style-name='Aside Text'] => div.aside > p:fresh
``` 

returns 

```Did not understand this style mapping, so ignored it:
Error was at character number 1: Expected element type but got end```

**Comment by mwilliamson** [comment] 2016-09-16 11:30
I think the problem is a blank line in the style map, which is being parsed rather than ignored. Could you try the latest version and see if the problem persists?

**Comment by mwilliamson** [comment] 2016-09-19 17:58
Closing since I believe this is fixed, but feel free to reopen if that's not the case.

**Closed by mwilliamson** 2016-09-19 17:58 UTC
