### ISSUE TITLE
transformDocument is missing

### ISSUE THREAD

**Issue by natikos** [mwilliamson/mammoth.js#353] opened 2023-03-03 09:52 UTC
I am using:
- node.js `16.19.0`
- mammoth `1.5.1`
- yarn `1.22.19`

After successful install of package, I got  the following Options interfaces inside my node_modules:
```ts
interface Options {
    styleMap?: string | Array<string>;
    includeEmbeddedStyleMap?: boolean;
    includeDefaultStyleMap?: boolean;
    convertImage?: ImageConverter;
    ignoreEmptyParagraphs?: boolean;
    idPrefix?: string;
}
``` 

there is no `transformDocument` property from docs.

**Comment by robin-garnham** [comment] 2023-03-07 00:41
I noticed this too. It actually still works but Typescript gives warnings and has to be disabled for that line

**Comment by mwilliamson** [comment] 2023-03-07 09:27
Closing as a duplicate of https://github.com/mwilliamson/mammoth.js/issues/315.

**Closed by mwilliamson** 2023-03-07 09:27 UTC
