### ISSUE TITLE
Single list incorrectly being split into multiple lists

### ISSUE THREAD

**Issue by privatmamtora** [mwilliamson/mammoth.js#121] opened 2017-07-14 18:49 UTC
Lists with breaks don't seem to convert properly to a single HTML list, but instead gets converted to individual lists.
The word document does know that it is a single list.
[List Sample.docx](https://github.com/mwilliamson/mammoth.js/files/1149368/List.Sample.docx)

Current Result
```HTML
<ol>
    <li>Hello there.</li>
</ol>
<p>Part of a.</p>
<ol>
    <li>Item 2.</li>
</ol>
<p>Part of b</p>
<ol>
    <li>Item 3.</li>
</ol>
<p>Part of c</p>
<p>
    <br />
    <strong>Part of c2</strong>
</p>
```
Expected Result
```HTML
<ol style='list-style-type: lower-alpha;'>
    <li>Hello there.<p>Part of a.</p></li>
    <li>Item 2.<p>Part of b</p></li>
    <li>Item 3.
        <p>Part of c</p>
        <p>
            <br />
            <strong>Part of c2</strong>
        </p>
    </li>
</ol>
```

Environment
os: windows 7
node ver: 6.9.1

**Comment by mwilliamson** [comment] 2017-07-14 20:35
> The word document does know that it is a single list.

I'm not sure that's true. When I look at the document, I see a paragraph that's a bullet point, followed by a paragraph that is indented, so visually part of the list, but not actually part of the list. What makes you think Word knows it's part of the list?

Have you tried using a soft return (Shift+Enter) instead? That creates a new line without creating a new paragraph. The other alternative would be be to apply a style to the extra paragraphs and use an appropriate style mapping. For instance, if you gave them the style `Ordered List 1 Continuation`, then you could use the mapping:

```
p[style-name='Ordered List 1 Continuation'] => ol > li > p:fresh
```

**Comment by privatmamtora** [comment] 2017-07-16 22:09
@mwilliamson This is the reason why i think the word document knows that the list is the same:
![image](https://user-images.githubusercontent.com/7475401/28251716-1ea36d9a-6a51-11e7-912e-8449f885ebf1.png)
When a bullet item of a list is clicked, all other bullets of the same lists get highlighted. (So somehow it knows)
PS: My source documents are 100pg+ each, so editing them is not an option.

---

Is there a way to maintain list style? (Bullet type)

**Comment by mwilliamson** [comment] 2017-07-17 11:41
Word might know that those bullets are part of the same list, but does it know that those additional paragraphs are part of the list? In other words, if the caret is within, say, "Part of a", are those bullets still highlighted?

**Comment by privatmamtora** [comment] 2017-07-18 00:30
No it does not.
![image](https://user-images.githubusercontent.com/7475401/28295248-5ffb5f5a-6b2d-11e7-998a-640fb8816b4c.png)
It seems that internally also, word just treats it as 2 paragraphs.

But even if there are additional paragraphs, it should still be converted into a **single** list and not **multiple** lists.

**Comment by mwilliamson** [comment] 2017-07-18 07:53
The problem is that there's no reliable way of telling whether an
indented paragraph is meant to be part of the list or not. If you can
think of some sensible heuristics, then you could write them as
document transforms to handle this case. If there's extra information
that's need from the parser, such as the indentation of paragraphs, for
such a document transform then I'm happy to add it.

**Comment by privatmamtora** [comment] 2017-07-18 16:36
Ok other than the indented paragraph. (Yes the indent from the parser would be useful for a custom document transform)

---

Is there any way for the parser to recognize that the 2 list items (Example: "Hello there" & "Item 2.") should be put in a single `<ol>`? 

So expected result (invalid HTML) could be:
```HTML
<ol>
    <li>Hello there.</li>
    <p>Part of a.</p>
    <li>Item 2.</li>
    <p>Part of b</p>
    <li>Item 3.</li>
</ol>
<p>Part of c</p>
<p>
     <br />
     <strong>Part of c2</strong>
</p>
```
This could be fine if the definition of this tool is to "Parse a word document to HTML" vs "Parse a word document to **valid** HTML"

**Comment by mwilliamson** [comment] 2017-07-18 17:19
The simplest approach would be for the document transform to apply a style to each of the continuation paragraphs, such as `Ordered List 1 Continuation`. Then, if you use a style mapping such as:

```
p[style-name='Ordered List 1 Continuation'] => ol > li > p:fresh
```

then the following HTML would be generated:

```html
<ol>
    <li>Hello there.<p>Part of a.</p></li>
    <li>Item 2.<p>Part of b</p></li>
    <li>Item 3.<p>Part of c</p></li>
</ol>
```

which seems closer to what you want, I think.

**Comment by privatmamtora** [comment] 2017-07-18 18:09
Yes, yes it is. 👍 
Any chance you, can share what this document transform would look like? (Never used it before)

**Comment by mwilliamson** [comment] 2017-07-18 20:13
I think the latter: you want to apply the style to the indented paragraphs, so you want to check the current paragraph is indented and the previous paragraph is part of a list.

**Comment by privatmamtora** [comment] 2017-07-19 15:04
How do I access the current paragraph "indent", and do an `if` on the previous paragraph? (Inside the transform)

**Comment by mwilliamson** [comment] 2017-07-19 16:03
The indent is currently not available, but I wouldn't object to it
being added to the parser. The transform has access to the entire tree
of the parsed document, so you can use whatever logic you like to
transform it.

**Comment by privatmamtora** [comment] 2017-08-15 15:33
Hello @mwilliamson can I get some help exposing the "indent" property.

**Comment by mwilliamson** [comment] 2017-08-15 16:46
Try taking a look at `lib/docx/body-reader.js` and the corresponding tests. There's already some code that reads the paragraph properties, so you could add in an extra property to the parsed paragraph.

**Comment by privatmamtora** [comment] 2017-08-17 20:47
@mwilliamson I created a pull request for parser indents update. Currently it is only available for transforms. Do you think these properties should be processed in `document-to-html.js`? (Adding css to html result)

**Comment by mwilliamson** [comment] 2017-11-23 19:39
Closing now that the pull request has been merged.

**Closed by mwilliamson** 2017-11-23 19:39 UTC
