### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by davidjohnson90** [mwilliamson/mammoth.js#118] opened 2017-05-29 10:02 UTC
I am trying to use the mammoth package in my application. When I do npm install and use the functionality, it is throwing the below error.
                 **_"Uncaught TypeError: Cannot read property 'bind' of undefined"_**

I am using this functionality in the meteor and react application. Understood that this issue is due to the library files issue, as might be they will be using the same classes. Please check and help in the resolution of this issue.

**Comment by mwilliamson** [comment] 2017-05-29 10:32
Sounds like a duplicate of #111, although hard to be certain without a stack trace. Feel free to reopen if I'm mistaken.

**Closed by mwilliamson** 2017-05-29 10:32 UTC

**Comment by davidjohnson90** [comment] 2017-05-29 13:06
Hi mwilliamson,
Please find below the stacktrace for the same. Please help in the resolution.

**

modules.js?hash=0941e4e…:26340 Uncaught TypeError: Cannot read property 'bind' of undefined
    at meteorInstall.node_modules.mammoth.lib.docx.files.js (modules.js?hash=0941e4e…:26340)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at meteorInstall.node_modules.mammoth.lib.docx.docx-reader.js (modules.js?hash=0941e4e…:25189)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at meteorInstall.node_modules.mammoth.lib.index.js (modules.js?hash=0941e4e…:25052)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at Module.require (modules-runtime.js?hash=2b888cb…:130)
    at Module.Mp.importSync (modules.js?hash=0941e4e…:348)
    at meteorInstall.imports.ui.FileBrowse.jsx (FileBrowse.jsx:1)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at Module.require (modules-runtime.js?hash=2b888cb…:130)
    at Module.Mp.importSync (modules.js?hash=0941e4e…:348)
    at meteorInstall.client.main.jsx (main.jsx:1)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)

**

**Comment by mwilliamson** [comment] 2017-05-29 15:40
I don't use Meteor, so I'm not sure what the correct solution is. #111 describes what's going wrong and the principle of how to fix it.
