### ISSUE TITLE
Numbered sublist converted to HTML strangely

### ISSUE THREAD

**Issue by smith-kyle** [mwilliamson/mammoth.js#74] opened 2016-03-22 23:56 UTC
In both of these `docx` files I have a numbered list with nested sublists inside.
### Output of [example.docx](https://github.com/mwilliamson/mammoth.js/files/185179/example.docx)
```
<ol>
  <li><strong>FIRST MAJOR ITEM</strong></li>
</ol>
<ol>
  <li><strong>SECOND MAJOR ITEM</strong></li>
</ol>
<ul>
  <li>
    <ol>
      <li><strong>SUB-ITEM</strong></li>
    </ol>
  </li>
</ul>
<ul>
  <li>
    <ol>
      <li><strong>ANOTHER-SUB-ITEM</strong></li>
    </ol>
  </li>
</ul>
<p> </p>
<ul>
  <li>
    <ol>
      <li><strong>ANOTHER-SUB-ITEM</strong></li>
    </ol>
  </li>
</ul>
<ul>
  <li>
    <ol>
      <li><strong>ANOTHER-SUB-ITEM</strong></li>
    </ol>
  </li>
</ul>
<ol>
  <li><strong>THIRD-MAJOR ITEM</strong></li>
</ol>
<ol>
  <li><strong>FOURTH-MAJOR ITEM</strong></li>
</ol>
```

### Output of [example1.docx](https://github.com/mwilliamson/mammoth.js/files/185185/example1.docx)
```
<ol>
   <li>
      First item
      <ol>
         <li>A sub item</li>
         <li>Another sub item</li>
         <li>The last sub item</li>
      </ol>
   </li>
   <li>
      Second major item
      <ol>
         <li>Bah</li>
         <li>bah</li>
      </ol>
   </li>
</ol>
```

The second example appears correct, the html is pretty straightforward. However, the first example is wrapped in a lot of `li` and `ol` tags and the all of the lists are separated. Is there a way I can get around this?

**Comment by mwilliamson** [comment] 2016-03-23 00:13
Looks like this happens in the first document since there are empty paragraphs in the original Word document between each bullet. I've just published an updated version to npm. Does that produce the expected output?

**Comment by smith-kyle** [comment] 2016-03-23 01:22
That fixed it! And in record time. Thanks a bunch man that was super fast

**Comment by smith-kyle** [comment] 2016-03-23 15:58
Sorry I may have jumped the gun here. While it took care of some of the empty paragraphs it also kept some around. Here's the html output of the first example docx above using `v0.3.33`

```
<ol>
   <li><strong>FIRST MAJOR ITEM</strong></li>
   <li>
      <strong>SECOND MAJOR ITEM</strong>
      <ol>
         <li><strong>SUB-ITEM</strong></li>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
      </ol>
   </li>
</ol>
<p> </p>
<ul>
   <li>
      <ol>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
      </ol>
   </li>
</ul>
<ol>
   <li><strong>THIRD-MAJOR ITEM</strong></li>
   <li><strong>FOURTH-MAJOR ITEM</strong></li>
</ol>
```

I would expect the output to be something like
```
<ol>
   <li><strong>FIRST MAJOR ITEM</strong></li>
   <li>
      <strong>SECOND MAJOR ITEM</strong>
      <ol>
         <li><strong>SUB-ITEM</strong></li>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
         <li><strong>ANOTHER-SUB-ITEM</strong></li>
      </ol>
   </li>
   <li><strong>THIRD-MAJOR ITEM</strong></li>
   <li><strong>FOURTH-MAJOR ITEM</strong></li>
</ol>
```

**Comment by mwilliamson** [comment] 2016-03-23 18:27
It looks like the paragraph in the middle isn't empty -- it has a space in. If you get rid of the space, you should get the output you expect.

**Comment by stylerucom** [comment] 2016-03-24 09:35
I have the same problem. There is no additional space - only text on the new line between list items.
[example.docx](https://github.com/mwilliamson/mammoth.js/files/187533/example.docx)
```
<body>
	<p>Sample header</p>
	<p>Sample text</p>
	<ol>
		<li>First list item. Description.</li>
		<li>Second list item. Some more text.</li>
	</ol>
	<p>And description for the second item.</p>
	<ol>
		<li>Third list item.</li>
	</ol>
	<p>Other text.</p>
</body>
```

**Comment by mwilliamson** [comment] 2016-03-25 10:41
@stylerucom The problem with your document is that the description for the second item is not considered by Word to be part of the list. It's an ordinary paragraph that just happens to be indented to line up with the text of the bullets. If you want a newline in your bullet that gets turned into a `<br>`, then try using soft breaks (Shift+Enter) instead of creating a separate paragraph.

**Comment by stylerucom** [comment] 2016-03-31 13:11
My idea is in that generated html is not like docx.
Here is my docx:
![docx](https://cloud.githubusercontent.com/assets/1251525/14176732/23b08670-f75b-11e5-8a71-f2912a71d318.png)
And here is generated html:
![html](https://cloud.githubusercontent.com/assets/1251525/14176735/27adaa3c-f75b-11e5-81e5-c616c21a905c.png)

**Comment by mwilliamson** [comment] 2016-03-31 13:22
@stylerucom Thanks for the screenshot, but that doesn't change the explanation I gave above. Word doesn't consider the description for the second item to be part of a list, so neither does Mammoth. Using a soft break rather than creating a new paragraph for the description would be the easiest change in this case. Is that not appropriate for you?

The only other alternative I can think of would be to create a style mapping for the "List Paragraph" style, but that's likely to be rather error-prone since you can't tell which level of list it's currently in.

**Comment by mwilliamson** [comment] 2016-04-19 20:33
Closing since this is working as intended. Feel free to shout if what I've described above doesn't work for you.

**Closed by mwilliamson** 2016-04-19 20:33 UTC
