### ISSUE TITLE
Support for altChunks

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#78] opened 2016-04-19 00:02 UTC
I ran into trouble with a file that was generated via html-docx-js (on npm).   The output was blank with the following error: 

```js
  {
    "type": "warning",
    "message": "An unrecognised element was ignored: w:altChunk"
  }
```
After opening the file and manually saving-as I was able to perform the conversion.

**Comment by mwilliamson** [comment] 2016-04-19 20:26
Thanks for the report. This is a duplicate of #71, so feel free to continue the conversation there.

**Closed by mwilliamson** 2016-04-19 20:26 UTC

**Comment by MCTaylor17** [comment] 2016-04-21 18:05
I appologize, I searched issues for "altChunk" and didn't see that in the results.
