### ISSUE TITLE
math eqution not converted in html 

### ISSUE THREAD

**Issue by Anythingforlife** [mwilliamson/mammoth.js#125] opened 2017-07-21 10:43 UTC
if (element.name == "{http://schemas.openxmlformats.org/officeDocument/2006/math}oMath")
            element = Uploadformule.MathXml(element);

this math tag not supported

**Comment by mwilliamson** [comment] 2017-07-21 10:47
Duplicate of #83.

**Closed by mwilliamson** 2017-07-21 10:47 UTC
