### ISSUE TITLE
Headers and Footers are not coming

### ISSUE THREAD

**Issue by SureshKumar-Java** [mwilliamson/mammoth.js#266] opened 2021-01-13 03:34 UTC
Hello,

I am using mammoth to preview docx document . But the elements in Header and Footer are not populated.

Is mammoth support these features. If yes, Can you please let me know how to implement it.

Thank you in advance

**Comment by mwilliamson** [comment] 2021-01-13 21:44
Headers and footers are not supported, I'm afraid. Closing as a duplicate of #9.

**Closed by mwilliamson** 2021-01-13 21:44 UTC
