### ISSUE TITLE
Problems with numeric lists in word document

### ISSUE THREAD

**Issue by VTSgit** [mwilliamson/mammoth.js#406] opened 2024-06-17 08:04 UTC
I'm just getting acquainted with the library, and I have the problem, the essence of which is that in addition to this list, I have others, but the library perceives them incorrectly and makes their order different from what it is in the document itself. What are you suggesting maybe some part of the options TransformDocument or something else? If so, then it will not work with the entire document in my case, perhaps for the reason that I have several lists in the document, and I want to see them in the  which they are in word

I have approximately the following code where parse is from 'html-react-parser' and does not affect this
      

```
export const Component = () => {
  const documentHTML= await mammoth.convertToHtml({ arrayBuffer: buffer });

  return (
      <div className={......}>
        <div className={.....}>{parse(documentHTML)}</div>
      </div>
    )
} 
```
    

in my case without using options:
    
    1. .......
    ............
    1. .......
    3. ......
    4. ....
    5. .....
    6. .....
       ............
    1. ......
    
    
although it's all one big list in word.
   
screenshot:

![image](https://github.com/mwilliamson/mammoth.js/assets/70096379/b8cec5cb-d740-41c1-9026-c271613a1312)

example: 
[Microsoft Word (2).docx](https://github.com/user-attachments/files/15863843/Microsoft.Word.2.docx)

**Comment by mwilliamson** [comment] 2024-06-17 21:54
I believe this is a duplicate of #394?

**Comment by VTSgit** [comment] 2024-06-18 06:44
> I believe this is a duplicate of #394?

It seems to me that no, because there it would be possible to go through the entire document and correct it, but in my case I have text between the numbered lists and then other numbered lists. 


By the way, I still don’t understand what is meant by this, how can I use it in options?

> I noticed that you did not include the expected output HTML.
> 
> I think that this is what we need.
> 
> `<ol> <li>Text 1</li> </ol> <p>Some text</p> <ol start="2"> <li>Text 2</li> </ol> <p>Some text</p> <ol start="3"> <li>Text 3</li> </ol>`

**Comment by mwilliamson** [comment] 2024-06-18 07:49
In that case, I think this is a duplicate of #121.

**Comment by VTSgit** [comment] 2024-06-19 06:31
> In that case, I think this is a duplicate of #121.

Yes, apparently the problem still remained even after merging this branch:
https://github.com/mwilliamson/mammoth.js/pull/132

**Comment by mwilliamson** [comment] 2024-06-19 21:21
The issue is that the indented paragraphs are not themselves part of the bullet so far as the original Word document is concerned. As described in #121, you could try one of:
* using soft returns
* applying a list continuation style to the paragraphs and adding an appropriate style mapping for that style
* detecting the paragraphs from their indent using a document transform, applying a style to those paragraphs, and then adding an appropriate style mapping for that style.

**Closed by mwilliamson** 2024-06-19 21:21 UTC
