### ISSUE TITLE
Add Office Open XML support

### ISSUE THREAD

**Issue by Vishtar** [mwilliamson/mammoth.js#317] opened 2022-03-30 08:00 UTC
There are two .docx specification:

1. Word 2007
2. Office Open XML (https://www.loc.gov/preservation/digital/formats/fdd/fdd000400.shtml)

The difference beetwen them is in "XML namespace declaration": it's "w:body", "w:document", etc. in Word 2007 and "{http://purl.oclc.org/ooxml/wordprocessingml/main}body", "{http://purl.oclc.org/ooxml/wordprocessingml/main}document", etc. in Office Open XML.

Quote about a "{http://purl.oclc.org/ooxml/wordprocessingml/main}":

> This namespace declaration is for the Strict variant of DOCX. It occurs in the mandatory Main Document part of a DOCX file (package) with the name /word/document.xml and is mapped to the prefix w.

For testing i just replace all "w:" with "{http://purl.oclc.org/ooxml/wordprocessingml/main}" and it worked!

If you're requesting a feature, please include:

* a minimal example document: [Тест-план.docx](https://github.com/mwilliamson/mammoth.js/files/8378259/-.docx)

**Comment by mwilliamson** [comment] 2022-05-08 19:27
Closing as a duplicate of #146.

**Closed by mwilliamson** 2022-05-08 19:27 UTC
