### ISSUE TITLE
Is it normal that greek characters are converted in html entities ?

### ISSUE THREAD

**Issue by EmidioStani** [mwilliamson/mammoth.js#80] opened 2016-04-20 16:28 UTC
Hello,

we are working with a convertion of a docx containing greek characters using mammothjs with nodejs. The html output contains the respective html entities and not the greek characters.

Is it normal ?

**Comment by mwilliamson** [comment] 2016-04-20 17:24
Are you saying that the output is correct, but contains HTML entities
and you'd rather have the literal Unicode characters? Or that the
output is double-escaped and displaying incorrectly?

**Comment by EmidioStani** [comment] 2016-04-20 20:39
In the document.xml file, opened with Notepad++, I can see the greek characters, after doing the transformation if I open the html fragment I can see the HTML entities and I would expect to see the greek characters.

**Comment by mwilliamson** [comment] 2016-04-20 22:16
If you provide a small example document, I'll take a look when I get a chance. Mammoth itself doesn't escape non-ASCII characters to HTML entities, so I'm guessing that the XML reader that Mammoth uses is doing something with them.

**Comment by jensscheerlinck** [comment] 2016-04-21 06:48
Hi Michael, please find attached a sample Word document.
We are using MammothJS as a library in NodeJS.

[Uploading sample.docx…]()

**Comment by mwilliamson** [comment] 2016-04-22 19:46
I've just converted that document and don't see any HTML entities, just the unescaped Unicode characters. Could I see what code you're using to do the conversion? What version of node and OS are you running on?

**Comment by mwilliamson** [comment] 2016-05-04 21:46
Hello! Are you still having this issue, or can this be closed?

**Comment by mwilliamson** [comment] 2016-05-26 21:35
Closing since I don't think there's anything I can do at the moment. Feel free to reopen if you can provide reproduction steps.

**Closed by mwilliamson** 2016-05-26 21:35 UTC
Labels: Cannot reproduce
