### ISSUE TITLE
Ordered lists that are nested two or three deep are not supported by default

### ISSUE THREAD

**Issue by michaelbdavidson7** [mwilliamson/mammoth.js#306] opened 2022-01-04 16:01 UTC
Issue: When nesting ordered lists two or three layers deep in a docx file, the destination HTML file ordered lists merely are added to one ordered list at the top level, rather than nesting.

Examples: 
Source: 
![image](https://user-images.githubusercontent.com/6875673/148086653-c58929b0-e98d-4bba-ba2f-08779a8b4414.png)

Destination: 
![image](https://user-images.githubusercontent.com/6875673/148086710-b969a38a-be9c-4b18-b295-e0d5be6d219e.png)

Workaround: I managed to do a workaround with the following style map:
```p[style-name='List` Number 2'] => ol > ol > li:fresh```
```p[style-name='List Number 3'] => ol > ol > ol > li:fresh```

Workaround example:
![image](https://user-images.githubusercontent.com/6875673/148086867-ffc749b2-3b70-4c9a-9e77-27605856e543.png)
(I don't really care at all that the workaround has mere numbered lists in the second and third indention rather than `a.` and `(a)` respectively.)

I reproduced this issue with the current latest pip version, which i ran from the CLI. I also reproduced the issue from the Wordpress plugin. 

I'm not sure how this product works under the hood but if you can merely add those styles to the default style map I would recommend that. 

Thank you for making this possible and for continuing to support it!!!

**Comment by mwilliamson** [comment] 2022-01-04 17:31
Could you post a minimal example document so that I can take a look?

**Comment by michaelbdavidson7** [comment] 2022-01-04 18:33
Sure, here you go.
[044-ComplianceEthicsRiskAreas.docx](https://github.com/mwilliamson/mammoth.js/files/7809655/044-ComplianceEthicsRiskAreas.docx)

**Comment by mwilliamson** [comment] 2022-01-05 20:13
From a quick look, it looks like the issue is that the various paragraph styles "List Number N" are linked to the top level of a numbering style. In other words, so far as the document itself is concerned, all of the lists are top-level lists. One of way of seeing this in the editor is that there's no way to dedent the subitems in the list -- so far as the document is concerned, they're not subitems.

Where did the styles come from? If they're defined by yourself (rather than being builtin styles), the best solution would be to write a style map, as you already have. A suggested tweak to what you posted would be:

```
p[style-name='List Number 2'] => ul|ol > li > ol > li:fresh
p[style-name='List Number 3'] => ul|ol > li > ul|ol > li > ol > li:fresh
```

**Comment by mwilliamson** [comment] 2022-01-30 11:35
Closing since this looks like an issue with the source document, not Mammoth.

**Closed by mwilliamson** 2022-01-30 11:35 UTC
