### ISSUE TITLE
Problem_3: Issue with list items: 'ol'--> alphabetical converted to 'ol'--> Numbers

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#201] opened 2019-08-05 08:30 UTC
Hello,
The ordered list with alphabetical type (lowercase) has been converted to numerical type,
PFA,
![issue_3](https://user-images.githubusercontent.com/29540745/62450160-66867080-b789-11e9-813b-375d596327b9.PNG)
![Issue_3_html](https://user-images.githubusercontent.com/29540745/62450161-66867080-b789-11e9-9707-9853f3acf459.PNG)

**Comment by mwilliamson** [comment] 2019-08-13 19:35
This is a duplicate of https://github.com/mwilliamson/mammoth.js/issues/162: the expectation is that the formatting of lists would be controlled by the CSS in the document that the generated HTML ends up in, mapping Word styles to CSS classes if that level of control is needed.

**Closed by mwilliamson** 2019-08-13 19:35 UTC
