### ISSUE TITLE
The parsing effect of Chinese is not very good

### ISSUE THREAD

**Issue by edifangyi** [mwilliamson/mammoth.js#340] opened 2022-09-15 07:56 UTC
Thanks, but the support for Chinese is not very good

docx：
![image](https://user-images.githubusercontent.com/12421552/190348055-7620979a-8c54-4cfc-befa-920009944f1d.png)

HTML：
![image](https://user-images.githubusercontent.com/12421552/190347820-2c119860-6b14-484b-8868-fa2a819133d9.png)

**Comment by mwilliamson** [comment] 2022-09-15 08:03
Could you include a minimal example document, the expected HTML, and the actual HTML?

**Comment by edifangyi** [comment] 2022-09-15 08:21
Thanks~
[Demo.zip](https://github.com/mwilliamson/mammoth.js/files/9573341/Demo.zip)

**Comment by edifangyi** [comment] 2022-09-15 08:45
Sorry, I didn't read it carefully
`Mammoth is designed to convert .docx documents, such as those created by Microsoft Word, Google Docs and LibreOffice, and convert them to HTML. Mammoth aims to produce simple and clean HTML by using semantic information in the document, and ignoring other details. For instance, Mammoth converts any paragraph with the style Heading 1 to h1 elements, rather than attempting to exactly copy the styling (font, text size, colour, etc.) of the heading.`

**Comment by mwilliamson** [comment] 2022-09-19 08:46
> Sorry, I didn't read it carefully `Mammoth is designed to convert .docx documents, such as those created by Microsoft Word, Google Docs and LibreOffice, and convert them to HTML. Mammoth aims to produce simple and clean HTML by using semantic information in the document, and ignoring other details. For instance, Mammoth converts any paragraph with the style Heading 1 to h1 elements, rather than attempting to exactly copy the styling (font, text size, colour, etc.) of the heading.`

I'm not sure I follow. Are you saying that Mammoth is working as intended, according to that description?

**Comment by edifangyi** [comment] 2022-09-29 03:54
> > Sorry, I didn't read it carefully `Mammoth is designed to convert .docx documents, such as those created by Microsoft Word, Google Docs and LibreOffice, and convert them to HTML. Mammoth aims to produce simple and clean HTML by using semantic information in the document, and ignoring other details. For instance, Mammoth converts any paragraph with the style Heading 1 to h1 elements, rather than attempting to exactly copy the styling (font, text size, colour, etc.) of the heading.`
> 
> I'm not sure I follow. Are you saying that Mammoth is working as intended, according to that description?

According to the instructions, it should be as expected. " mammoth.js' only provides a simple output, but If only we could support Chinese better
~thank you

**Comment by mwilliamson** [comment] 2022-09-29 16:29
I just took a look at the example you gave: I don't suppose it'd be possible to have an even smaller example that contains the bare minimum required? Since I don't read or write Chinese, it's a little tricky for me to discern exactly what the issue is.

Similarly, it looks like the expected HTML has a bunch of inline styles (e.g. setting margin). This is something that Mammoth is unlikely to ever do. I'm assuming that's not inherent to supporting Chinese? If that's the case, then it'd be useful to have a minimal example of what the expected HTML would be.

**Comment by mwilliamson** [comment] 2024-02-03 11:58
Closing due to lack of information.

**Closed by mwilliamson** 2024-02-03 11:58 UTC
Labels: enhancement
