### ISSUE TITLE
Bug : uncompressed data size mismatch

### ISSUE THREAD

**Issue by Safee-ullah1** [mwilliamson/mammoth.js#419] opened 2024-09-07 07:33 UTC
I keep getting this error no matter which docx file I use.

it started from langchain, then I tried to use mammoth directly but same issue:

```javascript
async function extractRawTextFromDocx(arrayBuffer: ArrayBuffer) {
  try {
    const result = await extractRawText({ arrayBuffer });
    return result.value; // Extracted text
  } catch (error) {
    if (error instanceof Error) {
      console.error("Error extracting text from DOCX:", error);
      throw new Error(`Failed to extract text from DOCX: ${error.message}`);
    }
  }
}
```

**Comment by Safee-ullah1** [comment] 2024-09-09 02:15
Yeah, that's true, I'm sorry for the incomplete question.

My code is pretty much exactly the same. When running mammoth through the cli, with `pnpx mammoth file-sample_100kB.docx1` the output is okay.

**Comment by mwilliamson** [comment] 2024-09-09 09:37
> ## 4. CLI test
> 
> I haven't tested with the CLI as I'm running this in a Next.js environment.

Could you try using the CLI? This will help to determine if the issue is with Mammoth itself or the way you're using it.

> My code is pretty much exactly the same. When running mammoth through the cli, with `pnpx mammoth file-sample_100kB.docx1` the output is okay.

That suggests that the issue is that the array buffer you're passing to Mammoth is incorrect, so I'd suggest verifying that it has the correct contents. I'm afraid I can't provide any help without further details.

**Comment by Safee-ullah1** [comment] 2024-09-10 00:02
```typescript
const processFile = async (url: string): Promise<ArrayBuffer> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("Network response was not ok");
  }
  const arrayBuffer = await response.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  return await mammoth.extractRawText({ buffer });
};

```

Seems like this code, when run inside a vercel serverless function produces this error.
I was getting this exact error on langchain and tried to use mammoth manually to tr and fix it but ran into the same error. Another common factor is both us are downloading the file over the internet from bucket storage. I'm using S3 to store the files.

**Comment by 3dteemu** [comment] 2024-09-11 13:01
I have the same problem.

This gives the error:
```
"use client";
import { convertToHtml } from "mammoth"; // Only this changes
...

const html = (await convertToHtml({ arrayBuffer: buffer }, options)).value;
```


This works:
```
"use client";
import { convertToHtml } from "mammoth/mammoth.browser"; // Only this changes
...

const html = (await convertToHtml({ arrayBuffer: buffer }, options)).value;
```

I use Next.js 14 and the code runs in the browser.

**Comment by mwilliamson** [comment] 2024-09-11 19:47
I'm afraid without a minimal, complete example of how to reproduce the problem, there's not much I can do to investigate. So far as I can tell (and apologies if I've missed it), all of the examples posted so far are fragments of larger programs.

If you want to investigate yourselves (which is likely to be the best route for environments such as next.js and vercel that I'm unfamiliar with), then Mammoth is just passing the buffer to `JSZip.loadAsync()`, and then reading the entries using `zipFile.file(name).async("uint8array")` method. Seeing if you can reproduce and then investigate the problem using JSZip directly is probably a good place to start.

**Comment by 3dteemu** [comment] 2024-09-12 11:52
I was about to create a minimal example that would reproduce this issue. While doing that I found out that (at least for me) the problem is with Turbopack.

This does not work:
```
next dev --turbo
```

This works:
```
next dev
```

Without Turbopack it is possible to import mammoth with
```
import mammoth from 'mammoth';
```
without using the browser version and everything works.

Since Turbopack is still in beta in Next.js, and I don't have the skills to debug it, I'll just use Webpack.
For me this is solved for now.

**Comment by lesenelir** [comment] 2024-09-12 15:40
> This does not work:
> 
> ```
> next dev --turbo
> ```
> 
> This works:
> 
> ```
> next dev
> ```

Thanks so much!

**Comment by mwilliamson** [comment] 2024-12-23 07:38
Sounds like this is potentially a (fixed) bug in Turbopack, and there aren't any reproduction steps for this issue, so I don't have a way of investigating further, so I'm closing this.

**Closed by mwilliamson** 2024-12-23 07:38 UTC
