### ISSUE TITLE
It ignores Math symbols and it's formatting after conversion

### ISSUE THREAD

**Issue by huzaynbolt** [mwilliamson/mammoth.js#241] opened 2020-05-17 11:04 UTC
It seems not to obey MathML symbols after conversion, Mathematical Equations aren't respected as well. 
E.g

3x – 6 = 8x – 20; 3x – 8x = - 20 + 6;  
	 -5x = -14;  x = 14/5
y=ax2+bx + c

**Comment by mwilliamson** [comment] 2020-05-17 13:21
Hello! I believe this is a duplicate of #83, so I'm closing this issue.

**Closed by mwilliamson** 2020-05-17 13:21 UTC
