### ISSUE TITLE
Read word file which contain clipart symbols 

### ISSUE THREAD

**Issue by iAssureIT** [mwilliamson/mammoth.js#190] opened 2019-03-04 16:51 UTC
Hello there,

I am having word file which contains the clipart code, which I need to read and uploaded into the database. 

Example is as follow:

![image](https://user-images.githubusercontent.com/16340191/53748879-3aaa4a80-3ecc-11e9-8b35-225ef766ce0b.png)

Other example is:
![image](https://user-images.githubusercontent.com/16340191/53748998-73e2ba80-3ecc-11e9-9d22-b2a4d9723998.png)

Please help in this.

**Comment by mwilliamson** [comment] 2019-03-04 19:54
Is this clipart, or is this using the equation editor?

**Comment by iAssureIT** [comment] 2019-03-05 05:16
yes this is clipart...

**Comment by mwilliamson** [comment] 2019-03-05 07:14
I might be misremembering, but isn't a clipart a library of images? I'm not sure how you can use clipart to produce equations?

**Comment by iAssureIT** [comment] 2019-03-06 14:58
Sorry for late reply. When I am clicking on the equation, I am able to see following windows:

![image](https://user-images.githubusercontent.com/16340191/53890493-550c3180-404e-11e9-9155-0d290ea2e0f5.png)

**Comment by mwilliamson** [comment] 2021-08-01 10:36
I think this is a duplicate of #83.

**Closed by mwilliamson** 2021-08-01 10:36 UTC
Labels: enhancement
