### ISSUE TITLE
Importing graphs and emf images

### ISSUE THREAD

**Issue by BahyQorrect** [mwilliamson/mammoth.js#389] opened 2023-12-19 16:03 UTC
I am using Mammoth in my angular project to read and convert the data from a word file while importing. it works fine
but when I use "chemdraw" as example in the word file and try to import the file in my project it appears like broken image and it show this two messages 
1- "Image of type image/x-emf is unlikely to display in web browsers"
2- "An unrecognised element was ignored: {urn:schemas-microsoft-com:office:office}OLEObject"
is there any solution for this?

**Comment by mwilliamson** [comment] 2023-12-19 16:14
Unfortunately, EMF images are not supported. Closing as a duplicate of #36.

**Closed by mwilliamson** 2023-12-19 16:14 UTC
