### ISSUE TITLE
Mammoth not returning anything [Windows 7, 32-bit node]

### ISSUE THREAD

**Issue by deepsyx** [mwilliamson/mammoth.js#29] opened 2014-11-24 06:11 UTC
Hello. I tried installing mammoth, but I didn't succeeded. I tried typing 

    var mammoth = require("mammoth");

    mammoth.convertToHtml({path: "E:\\Smartly.docx"})
    .then(function(result){
        var html = result.value; // The generated HTML
        var messages = result.messages; // Any messages, such as warnings during conversion
        console.log(html, message);
    })
    .fail(function(){
    	console.log('asdsad');
    })
    .done(function(){
    	console.log('please');
    }); 

in a test.js file, but when I run it, it instantly closes and no error or message are returned. I'm sure file exists and it's a valid docx. 

OS: NodeJs 32bit on Windows 7

Any ideas, why I cannot run it @mwilliamson?

Thanks.

**Comment by mwilliamson** [comment] 2015-04-08 17:00
I couldn't reproduce when I tried this myself on Windows 7 using 32-bit node, so closing. Feel free to reopen if this is still an issue.

**Closed by mwilliamson** 2015-04-08 17:00 UTC
Labels: bug, Cannot reproduce
