### ISSUE TITLE
Problem with bookmark tags

### ISSUE THREAD

**Issue by pmzi** [mwilliamson/mammoth.js#364] opened 2023-05-24 20:05 UTC
Hi,

I am using mammoth in Node.JS, and I would expect mammoth to detect bookmarks correctly and wrap them with a tag containing an id with the bookmark name. It does detect the bookmark but it does not wrap the correct text with the bookmark.

I have attached a docx file that if we convert it to HTML using mammoth, the output will be the following:
[newDoc.docx](https://github.com/mwilliamson/mammoth.js/files/11558621/newDoc.docx)

```html
<p>Salam <a id="SHARE_PREF_%25255Bpmzi%25255D"></a>khubi? Salam salam</p><p><a id="Bookmark_1"></a>bib s</p>
```

Which is incorrect! Because `<a id="SHARE_PREF_%25255Bpmzi%25255D"></a>` should be wrapped around `khubi?` and `<a id="Bookmark_1"></a>` should be wrapped around `bib`.

**Comment by mwilliamson** [comment] 2023-05-26 22:54
I'd be inclined to say it's safer not to wrap the elements, in case the styling for the target page styles all `a` elements (for instance) as links, regardless of whether or not they have an `href` attribute.

Can I ask why it makes a difference in your case?

**Comment by mwilliamson** [comment] 2023-06-02 09:13
I'm closing this since this as working as intended.

**Closed by mwilliamson** 2023-06-02 09:13 UTC

**Comment by NourIM** [comment] 2024-01-15 17:37
Hi @mwilliamson! I have the same concern here. First, why are you using <a> tag to say this is a bookmark? Is not the <span> safer in this case? and wrap the text that should have the bookmark? 

I'm finding some challenges in converting the exported HTML to a specific AST.
